platform: Any CPU
configuration:
- Debug
- Release
image: Visual Studio 2017
install:
- git submodule update --init --recursive
- ps: .\BuildTools\appveyor-install.ps1
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
before_build:
- nuget restore ILSpy.sln
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
build_script:
- msbuild ILSpy.sln /v:minimal /p:ResolveNuGetPackages=false "/logger:%ProgramFiles%\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
after_build:
- 7z a ILSpy_binaries.zip %APPVEYOR_BUILD_FOLDER%\ILSpy\bin\%configuration%\net461\*.dll %APPVEYOR_BUILD_FOLDER%\ILSpy\bin\%configuration%\net461\*.exe %APPVEYOR_BUILD_FOLDER%\ILSpy\bin\%configuration%\net461\*.config
test:
  assemblies:
    - 'ICSharpCode.Decompiler.Tests\bin\%configuration%\net461\ICSharpCode.Decompiler.Tests.exe'
    - 'ILSpy.BamlDecompiler.Tests\bin\%configuration%\net461\ILSpy.BamlDecompiler.Tests.dll'
after_test:
- python BuildTools\tidy.py
artifacts:
  - path: ILSpy_binaries.zip
    name: ILSpy %APPVEYOR_REPO_BRANCH% %ILSPY_VERSION_NUMBER% binaries
  - path: '**\*.nupkg'
    name: ICSharpCode.Decompiler %APPVEYOR_REPO_BRANCH% %ILSPY_VERSION_NUMBER% NuGet  