name: Build XPlat Frontends

on:
  push:
    branches: '**'
  pull_request:
    branches: [ master, release/** ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        persist-credentials: false
        
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
        dotnet-quality: 'preview'

    - name: Install dependencies
      run: dotnet restore ILSpy.XPlat.slnf -p:RestoreEnablePackagePruning=false

    - name: Build Debug
      run: dotnet msbuild ILSpy.XPlat.slnf -p:Configuration=Debug -bl:Debug.binlog

    - name: Build Release
      run: dotnet msbuild ILSpy.XPlat.slnf -p:Configuration=Release -bl:Release.binlog

    - name: list files
      if: always()
      run: ls -la

    - name: print VERSION
      if: always()
      run: cat VERSION

    - name: Upload binlog
      if: always()
      uses: actions/upload-artifact@v5
      with:
        name: binlog
        path: '**/*.binlog'
        if-no-files-found: error
