name: Build XPlat Frontends

on:
  push:
    branches: '**'
  pull_request:
    branches: [ master, release/** ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Install dependencies
      run: dotnet restore ILSpy.XPlat.slnf

    - name: Build Debug
      run: dotnet msbuild ILSpy.XPlat.slnf -p:Configuration=Debug -bl:Debug.binlog

    - name: Build Release
      run: dotnet msbuild ILSpy.XPlat.slnf -p:Configuration=Release -bl:Release.binlog

    - name: list files
      if: always()
      run: ls -la

    - name: print VERSION
      if: always()
      run: cat VERSION

    - name: Upload binlog
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: binlog
        path: '**/*.binlog'
        if-no-files-found: error
